// Dragoon Kit 

ADD_KIT ~MO_DRAGOON~
  ~MO_DRAGOON 1 1 1 1 1 1 1 1~
  ~MO_DRAGOON 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 1 1 5 1 1 1 1 1 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
  ~MO_DRAGOON 9 0 0 0 0 0~ // Minimum Ability - abclasrq
  ~MO_DRAGOON 0 0 0 0 0 0~ // Kit Ability Modifiers - abclsmod
  ~MO_DRAGOON 0 0 17 0 0 0~ // Requirement to Dual Class (to) - abdcedsrq
  ~MO_DRAGOON 0 0 15 0 0 0~ // Requirements to Dual Class (from) - abdcscrq
  ~MO_DRAGOON 1 1 1 1 1 1 1 1 1~ // Alignment
  ~MO_DRAGOON 0 1 1 1 1 0~ // Dual Class Options
  ~morpheus562-s-kitpack/2da/mo_dra01.2DA~ 
  ~K_F_H K_F_D K_F_G K_F_E K_F_HE K_F_HL K_F_HO~
  ~0x00004000 2~
  ~Fi0~
  ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
  SAY @5547
  SAY @5548
  SAY @5549

LAF fl#add_kit_ee STR_VAR kit_name = MO_DRAGOON END

OUTER_SET dragoon_code = (0x4000 + %MO_DRAGOON%)

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  SPRINT weapon_name ~%SOURCE_FILE%~
  READ_SHORT 0x1c type
  READ_ASCII 0x22 appearance (2)

  // Heavy Armor Restriction
  PATCH_IF (type = 2) AND (~%appearance%~ STRING_COMPARE_CASE ~4a~ = 0) BEGIN 
    LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 parameter1 = %dragoon_code% parameter2 = 9 power = 0 timing = 2 END
  END
  BUT_ONLY

COPY ~morpheus562-s-kitpack/2da/mo_dra01.2DA~        ~override~ // kit

/* OLD POLEARM DAMAGE INCREASES
ACTION_FOR_EACH polearm_master IN
      1
      3
      4
      5
      6
      7
      8
      9
    BEGIN
      COPY ~morpheus562-s-kitpack/spl/dragoon/modra0%polearm_master%.spl~                ~override~ // Polearm Master
      COPY ~morpheus562-s-kitpack/eff/dragoon/modra0%polearm_master%.eff~                ~override~ // Effect to cast actual spell
      COPY ~morpheus562-s-kitpack/spl/dragoon/modra%polearm_master%%polearm_master%.spl~ ~override~ // Spell that casts per level
    END
*/

/* OLD HAMSTRING ABILITY
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~Hamstring~) STR_VAR bam_file = SPWI221C RET MODRA2A = icon END
COPY ~morpheus562-s-kitpack/spl/dragoon/modra02.spl~ ~override~ // Hamstring
  SAY NAME1 @5550
  SAY UNIDENTIFIED_DESC @5551
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = ~MODRA2A~ END

COPY ~morpheus562-s-kitpack/eff/dragoon/modra02.eff~ ~override~ // Hamstring
COPY ~morpheus562-s-kitpack/spl/dragoon/modra22.spl~ ~override~ // Spell that casts Hamstring
*/

COPY ~morpheus562-s-kitpack/spl/dragoon/modra01.spl~  ~override~ // Fleet of Foot
COPY ~morpheus562-s-kitpack/bam/dragoon/modr327b.bam~ ~override~ // Leap Attack BAMb
COPY ~morpheus562-s-kitpack/bam/dragoon/modr327c.bam~ ~override~ // Leap Attack BAMc
COPY ~morpheus562-s-kitpack/2da/mo_dra02.2da~         ~override~ // Leap Attack 2da
COPY ~morpheus562-s-kitpack/spl/dragoon/modra02.spl~  ~override~ // Leap Attack
  SAY NAME1 @5600
  SAY UNIDENTIFIED_DESC @5601
  LPF ALTER_SPELL_EFFECT INT_VAR check_headers = 1 match_opcode = 214 STR_VAR resource = ~mo_dra02~ END
COPY ~morpheus562-s-kitpack/spl/dragoon/modra20.spl~  ~override~ // Chaotic Spring
  SAY NAME1 @5550
  SAY UNIDENTIFIED_DESC @5551
COPY ~morpheus562-s-kitpack/spl/dragoon/modra21.spl~  ~override~ // Heaven's Thrust
  SAY NAME1 @5602
  SAY UNIDENTIFIED_DESC @5603
COPY ~morpheus562-s-kitpack/spl/dragoon/modra03.spl~  ~override~ // Arm's Length