// Achmage Prestige kit for Mages

ADD_KIT ~MO_ARCHMAGE~
  ~MO_ARCHMAGE 0 0 0 0 0 0 0 0~ // clasweap.2da
  ~MO_ARCHMAGE 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~ //weapprof.2da
  ~MO_ARCHMAGE 0 0 0 9 0 0~ // Minimum Ability - abclasrq
  ~MO_ARCHMAGE 0 0 0 0 0 0~ // Kit Ability Modifiers - abclsmod
  ~MO_ARCHMAGE 0 0 0 0 0 0~ // Requirement to Dual Class (to) - abdcedsrq
  ~MO_ARCHMAGE 0 0 0 0 0 0~ // Requirements to Dual Class (from) - abdcscrq
  ~MO_ARCHMAGE 1 1 1 1 1 1 1 1 1~ // Alignment
  ~MO_ARCHMAGE 0 0 0 0 0 0~ // Dualclass
  ~morpheus562-s-kitpack/2da/MO_ARC01.2DA~ // CLAB
  ~~ 
  ~0x00004000 1~
  ~Ma0~ 
  ~* * * BAG29 RING06 RING40 * BOOT01 AMUL21 BRAC15 BELT10 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 SLNG05 DAGG05,20 STAF20~
  SAY @5571
  SAY @5572
  SAY @5573

LAF fl#add_kit_ee STR_VAR kit_name = MO_ARCHMAGE END

OUTER_SET archmage_code = (0x4000 + %MO_ARCHMAGE%)

///////////////////////////////////////////////////////////////////////////
// Import                                                                //
///////////////////////////////////////////////////////////////////////////
COPY ~morpheus562-s-kitpack/2da/MO_ARC01.2DA~         ~override~ // kit

ACTION_IF !FILE_EXISTS_IN_GAME ~CLABMA01.2DA~ THEN BEGIN
  COPY ~orpheus562-s-kitpack/2da/CLABMA01.2DA~        ~override~
END

COPY ~morpheus562-s-kitpack/spl/archmage/moarc01.SPL~ ~override~ // +1 Spell Caster Level
COPY ~morpheus562-s-kitpack/spl/archmage/moarc02.SPL~ ~override~ // Arcane Fire
  SAY NAME1 @5574
  SAY UNIDENTIFIED_DESC @5575
COPY ~morpheus562-s-kitpack/spl/archmage/moarc03.SPL~ ~override~ // Spell Weaver
  SAY NAME1 @5576
  SAY UNIDENTIFIED_DESC @5577
COPY ~morpheus562-s-kitpack/spl/archmage/moarc04.SPL~ ~override~ // Grand Mage
  SAY NAME1 @5578
  SAY UNIDENTIFIED_DESC @5579
COPY ~morpheus562-s-kitpack/spl/archmage/moarc05.spl~ ~override~ // Opcode 177
COPY ~morpheus562-s-kitpack/eff/archmage/moarc05.eff~ ~override~ // Set AI Script
COPY ~morpheus562-s-kitpack/cre/moweave.cre~          ~override~ // The Weave
  SAY NAME1 @5581
  SAY NAME2 @5581

COMPILE EVALUATE_BUFFER ~morpheus562-s-kitpack/dlg/moarc1.d~

///////////////////////////////////////////////////////////////////////////
// Update Fighter Kit                                                    //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~CLABMA01.2DA~ override
    LPF set_clab_2da_entries INT_VAR f_MinLevel = 18 f_MaxLevel = 18 STR_VAR f_Entry = AP_MOARC05 END
    PRETTY_PRINT_2DA
  BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Copy .BCS file to override folder                                     //
///////////////////////////////////////////////////////////////////////////
COPY ~morpheus562-s-kitpack/baf/moarc1.baf~ ~override/moarc1.bcs~
     ~morpheus562-s-kitpack/baf/moarc2.baf~ ~override/moarc2.bcs~
     ~morpheus562-s-kitpack/baf/moarc3.baf~ ~override/moarc3.bcs~
  COMPILE_BAF_TO_BCS  
